// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Actor struct {
	ID        string `json:"id"`
	Firstname string `json:"firstname"`
	Lastname  string `json:"lastname"`
}

type Movie struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Year  int    `json:"year"`
	Actor *Actor `json:"actor"`
}

type NewMovie struct {
	Name           string `json:"name"`
	Year           int    `json:"year"`
	ActorFirstname string `json:"actorFirstname"`
	ActorLastname  string `json:"actorLastname"`
}
